[params]
baseURL = 'https://example.org/'
# languageCode = 'en-us'
title = "lucasew's offtopic"
# defaultContentLanguage = 'en'

[languages.en]
title = "lucasew's offtopic"
languageName = "🇺🇸"
disabled = false

[languages.pt]
title = "offtopic do lucasew"
languageCode = "pt_BR"
languageName = "🇧🇷"
disabled = false

[module]
  [[module.mounts]]
    source = 'content'
    target = 'content'
    lang = 'en'
  [[module.mounts]]
    source = 'content'
    target = 'content'
    lang = 'pt'
