name: GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: https://lucasew.github.io/
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Run updaters
        run: ./update.sh

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'

      - name: Build
        env:
          URL: ${{ steps.deployment.outputs.page_url }}
        run: hugo --minify --baseURL "$URL"

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: ./public

      - name: Step summary
        env:
          URL: ${{ steps.deployment.outputs.page_url }}
        run: |
          printf "Deployed on: %s" "$URL" >> $GITHUB_STEP_SUMMARY

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
